// <auto-generated />
using System;
using Base.Persistence.DbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Base.Persistence.Migrations.Bank
{
    [DbContext(typeof(BankDbContext))]
    [Migration("20250501172946_InitialCreate_Bank")]
    partial class InitialCreate_Bank
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Papara.Domain.Entities.Bank.BankAccount", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AccountHolderName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<byte>("AccountType")
                        .HasColumnType("tinyint");

                    b.Property<string>("IBAN")
                        .IsRequired()
                        .HasMaxLength(34)
                        .HasColumnType("nvarchar(34)");

                    b.Property<string>("IdentityNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaxNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BankAccounts", "Bank");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            AccountHolderName = "Papara Şirketi",
                            AccountType = (byte)2,
                            IBAN = "TR000000000000000000000999",
                            TaxNumber = "1234567890"
                        },
                        new
                        {
                            Id = 2L,
                            AccountHolderName = "Özlem Kalemci",
                            AccountType = (byte)1,
                            IBAN = "TR000000000000000000000001",
                            IdentityNumber = "12345678901"
                        },
                        new
                        {
                            Id = 3L,
                            AccountHolderName = "Personel Personel",
                            AccountType = (byte)1,
                            IBAN = "TR000000000000000000000002",
                            IdentityNumber = "34567890123"
                        });
                });

            modelBuilder.Entity("Papara.Domain.Entities.Bank.ExpensePayment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("ExpenseId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsSuccessful")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("PaymentDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("PaymentReferenceNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ReceiverIBAN")
                        .IsRequired()
                        .HasMaxLength(34)
                        .HasColumnType("nvarchar(34)");

                    b.Property<string>("SenderIBAN")
                        .IsRequired()
                        .HasMaxLength(34)
                        .HasColumnType("nvarchar(34)");

                    b.Property<byte>("TransferType")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.ToTable("ExpensePayments", "Bank");
                });
#pragma warning restore 612, 618
        }
    }
}
